version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - 8000:8000
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel_user  # Создаем нового пользователя
            - DB_PASSWORD=laravel_password  # Пароль для нового пользователя

    db:
        image: mysql:8.0  # или любой другой образ вашей базы данных
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: userpassword

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - "8080:80"  # Подключение phpMyAdmin к порту 8080
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: rootpassword  # Установите пароль root для MySQL

volumes:
    dbdata:
